#!/bin/bash
# =============================================================
# scripts/destroy.sh
# Purpose: destroy Terraform-managed dev resources.
# =============================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
DEV_DIR="${PROJECT_ROOT}/terraform/envs/dev"
BACKEND_HCL="${DEV_DIR}/backend.hcl"
DEV_TFVARS="${DEV_DIR}/terraform.tfvars"
STATE_KEY="dev/terraform.tfstate"
STATE_BUCKET_PREFIX="devsecops-tfstate-"

write_backend_hcl() {
  local bucket_name="$1"

  cat > "${BACKEND_HCL}" <<EOF
# Generated by scripts/destroy.sh
bucket = "${bucket_name}"
EOF
}

resolve_state_bucket() {
  local configured_bucket=""

  if [ -f "${BACKEND_HCL}" ]; then
    configured_bucket="$(sed -n 's/^bucket = "\(.*\)"/\1/p' "${BACKEND_HCL}" | head -n 1)"
  fi

  if [ -n "${configured_bucket}" ] && aws s3api head-bucket --bucket "${configured_bucket}" >/dev/null 2>&1; then
    echo "${configured_bucket}"
    return 0
  fi

  mapfile -t buckets < <(
    aws s3api list-buckets \
      --query "Buckets[?starts_with(Name, '${STATE_BUCKET_PREFIX}')].Name" \
      --output text | tr '\t' '\n' | grep -v '^$'
  )

  if [ "${#buckets[@]}" -eq 0 ]; then
    echo ""
    return 0
  fi

  local stateful_buckets=()
  local bucket=""
  local last_modified=""

  for bucket in "${buckets[@]}"; do
    last_modified="$(
      aws s3api head-object \
        --bucket "${bucket}" \
        --key "${STATE_KEY}" \
        --query 'LastModified' \
        --output text 2>/dev/null || true
    )"

    if [ -n "${last_modified}" ] && [ "${last_modified}" != "None" ]; then
      stateful_buckets+=("${last_modified}|${bucket}")
    fi
  done

  if [ "${#stateful_buckets[@]}" -gt 0 ]; then
    printf '%s\n' "${stateful_buckets[@]}" | sort | tail -n 1 | cut -d'|' -f2
    return 0
  fi

  aws s3api list-buckets \
    --query "reverse(sort_by(Buckets[?starts_with(Name, '${STATE_BUCKET_PREFIX}')], &CreationDate))[0].Name" \
    --output text
}

read_tfvars_value() {
  local key="$1"

  if [ ! -f "${DEV_TFVARS}" ]; then
    echo ""
    return 0
  fi

  sed -n "s/^${key}[[:space:]]*=[[:space:]]*\"\\(.*\\)\"/\\1/p" "${DEV_TFVARS}" | head -n 1
}

cleanup_orphan_efs() {
  local aws_region="$1"
  local name_prefix="$2"
  local creation_token="${name_prefix}-efs"
  local resource_address="module.storage.aws_efs_file_system.shared"

  if terraform state list 2>/dev/null | grep -qx "${resource_address}"; then
    echo "EFS is already tracked in Terraform state."
    return 0
  fi

  mapfile -t file_system_ids < <(
    aws efs describe-file-systems \
      --region "${aws_region}" \
      --query "FileSystems[?CreationToken=='${creation_token}'].FileSystemId" \
      --output text | tr '\t' '\n' | grep -v '^$'
  )

  if [ "${#file_system_ids[@]}" -eq 0 ]; then
    echo "No orphan EFS found for creation token: ${creation_token}"
    return 0
  fi

  echo "Found orphan EFS resources for creation token '${creation_token}'."

  local fs_id=""
  local mount_target_id=""
  local remaining_mount_targets=""

  for fs_id in "${file_system_ids[@]}"; do
    echo "Deleting mount targets for ${fs_id}..."

    mapfile -t mount_target_ids < <(
      aws efs describe-mount-targets \
        --region "${aws_region}" \
        --file-system-id "${fs_id}" \
        --query 'MountTargets[].MountTargetId' \
        --output text | tr '\t' '\n' | grep -v '^$'
    )

    for mount_target_id in "${mount_target_ids[@]}"; do
      aws efs delete-mount-target \
        --region "${aws_region}" \
        --mount-target-id "${mount_target_id}"
    done

    while true; do
      remaining_mount_targets="$(
        aws efs describe-mount-targets \
          --region "${aws_region}" \
          --file-system-id "${fs_id}" \
          --query 'MountTargets[].MountTargetId' \
          --output text 2>/dev/null || true
      )"

      if [ -z "${remaining_mount_targets}" ] || [ "${remaining_mount_targets}" = "None" ]; then
        break
      fi

      sleep 10
    done

    echo "Deleting orphan EFS ${fs_id}..."
    aws efs delete-file-system \
      --region "${aws_region}" \
      --file-system-id "${fs_id}"

    aws efs wait file-system-deleted \
      --region "${aws_region}" \
      --file-system-id "${fs_id}"
  done
}

echo ""
echo "========================================="
echo "  Destroy Terraform Dev Resources"
echo "========================================="
echo ""
echo "  This will remove resources such as:"
echo "  - NAT Gateway / EIP / ALB"
echo "  - ECS services / tasks"
echo "  - ECR repositories and images"
echo "  - VPC / subnets / security groups"
echo "  - S3 artifacts / EFS / CloudWatch / IAM"
echo ""

read -r -p "  Continue? Type 'yes': " CONFIRM
if [ "${CONFIRM}" != "yes" ]; then
  echo "  Cancelled."
  exit 0
fi

if ! command -v aws >/dev/null 2>&1; then
  echo "aws CLI not found in PATH."
  exit 1
fi

if ! command -v terraform >/dev/null 2>&1; then
  echo "terraform not found in PATH."
  exit 1
fi

AWS_REGION="$(read_tfvars_value "aws_region")"
if [ -z "${AWS_REGION}" ]; then
  AWS_REGION="${AWS_REGION:-ap-northeast-2}"
fi

NAME_PREFIX="$(read_tfvars_value "name_prefix")"
if [ -z "${NAME_PREFIX}" ]; then
  echo "Could not read name_prefix from ${DEV_TFVARS}."
  exit 1
fi

echo ""
echo "[0/2] Resolving Terraform state bucket..."
STATE_BUCKET="$(resolve_state_bucket)"

if [ -z "${STATE_BUCKET}" ] || [ "${STATE_BUCKET}" = "None" ]; then
  echo "Could not find a Terraform state bucket with prefix '${STATE_BUCKET_PREFIX}'."
  echo "Run bootstrap/setup first or create backend.hcl with the correct bucket."
  exit 1
fi

write_backend_hcl "${STATE_BUCKET}"
echo "Using state bucket: ${STATE_BUCKET}"

cd "${DEV_DIR}"

echo ""
echo "[1/2] terraform init..."
terraform init \
  -input=false \
  -backend-config=backend.hcl \
  -reconfigure

echo ""
echo "[1.5/2] Cleaning orphan EFS if needed..."
cleanup_orphan_efs "${AWS_REGION}" "${NAME_PREFIX}"

echo ""
echo "[2/2] terraform destroy... (may take several minutes)"
echo ""
terraform destroy -input=false

echo ""
echo "========================================="
echo "  Destroy complete"
echo "========================================="
echo ""
echo "  The bootstrap S3 state bucket is preserved."
